### ISSUE TITLE
Fix response for to get all tags

### ISSUE THREAD

**Issue by egnaf** [Reckue/post-api#242]
Tested on: http://post-reckue.apps.us-east-1.starter.openshift-online.com/swagger-ui.html#//tags/findAllUsingGET_2

#### Reproduce:
1. Go to GET `/tags`.
2. Enter without params execute button.

#### ER: 
List of all tags.

#### AR: 
Status 500 Internal error.

<img width="400" alt="Screenshot 2020-06-12 at 21 37 39" src="https://user-images.githubusercontent.com/32206555/84535683-f293ed80-acf4-11ea-93af-c374cb447940.png">

**Comment by coungard** [comment]
@egnaf 
![изображение](https://user-images.githubusercontent.com/32792990/84577594-7a95f800-adc6-11ea-93ad-a0a7e07fe2d4.png)

**Comment by coungard** [comment]
@egnaf should i put some values before test this?

**Comment by egnaf** [comment]
> @egnaf should i put some values before test this?

No

**Comment by egnaf** [comment]
Fixed
