### ISSUE TITLE
Add test in tag service realization test 

### ISSUE THREAD

**Issue by Vikkingg13** [Reckue/post-api#249]
Hi!
Please add test for deleteById method where existsById equals true in tag service realization test.

It's all. Thanks.

**Comment by coungard** [comment]
@Vikkingg13 i quess this test is redundant.  
![изображение](https://user-images.githubusercontent.com/32792990/84577269-8e8c2a80-adc3-11ea-8982-16da37fd97c4.png)

isn't that avoid mock realization our repository?

**Comment by coungard** [comment]
@egnaf what u think?

**Comment by coungard** [comment]
@Vikkingg13 @egnaf I mean that at this point we do not expect any behavior regarding the ServiceTag

**Comment by egnaf** [comment]
@coungard see in other mock tests this case.

**Comment by Vikkingg13** [comment]
Viewed
