### ISSUE TITLE
Create Node with content

### ISSUE THREAD

**Issue by Hardelele** [Reckue/post-api#291]
1. Go to http://post-reckue.apps.us-east-1.starter.openshift-online.com/swagger-ui.html.
2. Add new node with content field value `{}` or any other value.

**Expected result:** 201 created
**Actual result:** 500

![image](https://user-images.githubusercontent.com/32300896/85921007-61d71900-b881-11ea-942b-89f9269118b3.png)
![image](https://user-images.githubusercontent.com/32300896/85920995-41a75a00-b881-11ea-9524-7f9cc54db983.png)

**Comment by Hardelele** [comment]
POST endpoint not working. Cant add any content.

**Comment by Hardelele** [comment]
Fix it quickly.

**Comment by egnaf** [comment]
> Fix it quickly.

Okay 👌

**Comment by egnaf** [comment]
Fixed
