### ISSUE TITLE
Required exceptions hierarchy

### ISSUE THREAD

**Issue by coungard** [Reckue/post-api#310]
**Need to add a hierarchy of all exceptions, where the base exception will be Reckue base exception.
Each exception must have its own error code.**

***Example:
PostNotFoundException -> ModelNotFoundException -> ReckueException***

*404 Not Found 
{
    "code" : "RE-001"
    "description" : "The post by id '11' is not found"
}*

**Comment by egnaf** [comment]
Resolved
