### ISSUE TITLE
Add repositories

### ISSUE THREAD

**Issue by egnaf** [reckue/post-api#48]
Hi!
Please add in package repositories interfaces for classes from package models that were defined in the story #33.

#### Example:
```java
package com.reckue.post.repositories;

// imports

@Repository
public interface NodeRepository exatends MongoRepository<Node, String> {
}
```

#### Repositories:
- #60 TextNodeRepository
- #50 ImageNodeRepository
- #51 VideoNodeRepository
- #52 CodeNodeRepository 
- #53 ListNodeRepository 
- #54 TagRepository 
- #55 NodeRepository 
- #56 PostRepository

**Comment by daria80** [comment]
We have closed all repositories
