### ISSUE TITLE
Add userId to notes

### ISSUE THREAD

**Issue by Hardelele** [reckue/post-api#7]
Add userId field to Note models and update methods / create new getByUserId methods.

Note models: 

```java
privat String id;
privat String userId;
```

NoteService interface:

```java
Note getByUserId(String userId);
```

And implement it.

```java
@Override
public Note getByUserId(String userId) {
    //  implement here
}
```

**Comment by egnaf** [comment]
@Hardelele please, add an example of what you want. 
Thanks. 🙂
