### ISSUE TITLE
Add data transfer object classes

### ISSUE THREAD

**Issue by egnaf** [reckue/post-api#75]
Hello!
Need to add [DTO](https://en.wikipedia.org/wiki/Data_transfer_object) level in the package `com.reckue.post.transfers` for models.

Please add `*Request` and `*Response` classes for models:

#76 TextNode
#77 ImageNode
#78 VideoNode
#79 CodeNode
#80 ListNode

#81 Tag

#82 Node
#83 Post

##### CodeNodeRequest.java
```java
package com.reckue.post.transfers;

import com.reckue.post.models.LangType;
import lombok.Data;

@Data
public class CodeNodeRequest {

    private LangType language;
    private String content;
}
```

##### CodeNodeResponse.java
```java
package com.reckue.post.transfers;

import com.reckue.post.models.LangType;
import lombok.Data;

@Data
public class CodeNodeResponse {

    private String id;
    private LangType language;
    private String content;
}
```

**Comment by daria80** [comment]
Add all data transfer object classes
