### ISSUE TITLE
Add services

### ISSUE THREAD

**Issue by egnaf** [reckue/post-api#99]
Hello!
Please add **services** for working with models with **javadoc**:

| id | Services |
|:------------- |:--------------|
| #100               | TextNodeService  |
| #101                | ImageNodeService  |
| #102                | VideoNodeService  |
| #103                | CodeNodeService  |
| #104                | TagService  |
| #105                | NodeService  |
| #106                | PostService  |

Need to create methods to [CRUD](https://en.wikipedia.org/wiki/CRUD).

package for interfaces: `com.reckue.post.services`
package: for implementations`com.reckue.post.services.realizations`

Methods:
- T create(T object)
- T update(T object)
- List<T> findAll(int limit, int offset, String sort, boolean desc)
- T findById(String id)
- void deleteById(String id)

It's all.

**Comment by camelya58** [comment]
All services are closed.
